- name: Copy app files
  synchronize: src={{source_directory}} dest={{ deploy_directory }} delete=yes rsync_opts=--exclude=.git/
  notify: Restart supervisor app

- name: Copy package.json
  copy:
    src: "{{ package_json_file }}"
    dest: "{{ deploy_directory }}/package.json"

- name: npm install
  shell: "npm install --production || true"
  args:
    chdir: "{{ deploy_directory }}"

- name: Create api/config/local-production.yml file
  copy: content="{{ api_config | to_nice_yaml }}" dest="{{ deploy_directory }}/config/local-production.yml"
